services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432/tcp

volumes:
  postgres_data: