services:
  app:
    build: .
    depends_on: 
    - postgres
    volumes: 
    - ./:/app
    - .env:/app/.env
    ports:
      - "8080:8080"
    tty: true
  postgres:
    image: postgres:15.3
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: